function labelthumbs(json){for(var i=0;i<numposts;i++){var entry=json.feed.entry[i];var posttitle=entry.title.$t;var posturl;var postauthor=entry.author[0].name.$t;if(i==json.feed.entry.length)break;for(var k=0;k<entry.link.length;k++){if(entry.link[k].rel=='replies'&&entry.link[k].type=='text/html'){var commenttext=entry.link[k].title;var commenturl=entry.link[k].href;}
if(entry.link[k].rel=='alternate'){posturl=entry.link[k].href;break;}}
var thumburl;try{thumburl=entry.gform_foot.url;}catch(error){s=entry.content.$t;a=s.indexOf("<img");b=s.indexOf("src=\"",a);c=s.indexOf("\"",b+5);d=s.substr(b+5,c-b-5);if((a!=-1)&&(b!=-1)&&(c!=-1)&&(d!="")){thumburl=d;}else thumburl='http://3.bp.blogspot.com/-O-vjxP03hYo/UXVtH90_iQI/AAAAAAAAAG4/60hz9Rn5FWA/s1600/No+Image+1.gif';}
var postdate=entry.published.$t;var cdyear=postdate.substring(0,4);var cdmonth=postdate.substring(5,7);var cdday=postdate.substring(8,10);var monthnames=new Array();monthnames[1]="يناير";monthnames[2]="فبراير";monthnames[3]="مارس";monthnames[4]="أبريل";monthnames[5]="مايو";monthnames[6]="يونيو";monthnames[7]="يوليو";monthnames[8]="أغسطس";monthnames[9]="سبتمبر";monthnames[10]="أكتوبر";monthnames[11]="نوفمبر";monthnames[12]="ديسمبر";document.write('<div class="newsBoxPost"><div class="newsBoxPostThumb ThumbCover"><div class="cover" style="top: 100%;"><a class="postype" href="'+ posturl+'"></a><a class="detail" href="'+ posturl+'" title="إقرا المقال"></a></div><a href="'+ posturl+'" rel="bookmark" title="'+ posttitle+'">');if(showpostthumbnails==true)
document.write('<img alt="'+ posttitle+'" src="'+ thumburl+'" style="width:120px; height:92px;"></a></div>');document.write('<h1 class="newsBoxPostTitle"><a href="'+ posturl+'">'+ posttitle+'</a></h1><ul class="postMeta"><li class="postAuthor"><a href="#" rel="author" title="الكاتب">'+postauthor+'</a></li><li class="postDate">'+monthnames[parseInt(cdmonth,10)]+'&nbsp;'+ cdyear+','+ cdday+'</li><li class="postComments">');if(showcommentnum==true){if(flag==1){towrite=towrite+' | ';}
if(commenttext=='1 Comments')commenttext='1 Comment';if(commenttext=='0 Comments')commenttext='No Comments';commenttext='<a href="'+ commenturl+'" target ="_top">'+ commenttext+'</a>';towrite=towrite+ commenttext;flag=1;;}
if("content"in entry){var postcontent=entry.content.$t;}else
if("summary"in entry){var postcontent=entry.summary.$t;}else var postcontent="";var re=/<\S[^>]*>/g;postcontent=postcontent.replace(re,"");var towrite='';var flag=0;document.write('</li></ul><p>');if(showpostsummary==true){if(postcontent.length<numchars){document.write('');document.write(postcontent);document.write('');}else{document.write('');postcontent=postcontent.substring(0,numchars);var quoteEnd=postcontent.lastIndexOf(" ");postcontent=postcontent.substring(0,quoteEnd);document.write(postcontent+'...');document.write('');}}
document.write(towrite);document.write('</p></div>');if(displayseparator==true)
if(i!=(numposts- 1))
document.write('');}
document.write('');}